### ISSUE TITLE
Using Unique ViewModel with UserWidget

### ISSUE THREAD

**Issue by Maxproz** [DoubleDeez/MDViewModel#1]
Referencing the following Code

```
#if WITH_EDITOR
void UMDViewModelProvider_Unique::GetExpectedContextObjectTypes(const FInstancedStruct& ProviderSettings, const FInstancedStruct& ViewModelSettings, UBlueprint* Blueprint, TArray<TSubclassOf<UObject>>& OutContextObjectClasses) const
{
	if (IsValid(Blueprint))
	{
		OutContextObjectClasses.Add(Blueprint->SkeletonGeneratedClass != nullptr ? Blueprint->SkeletonGeneratedClass : Blueprint->GeneratedClass);
	}
}
#endif
```

After assigning a Unique ViewModel provider on a UserWidget you get mismatched type errors because in your VM GetExpectedContextObject override you never put userwidget in there its always for example, ACharacter or GameInstance, the actual context etc. But the provider will always add your UserWidget blueprint as the expected context with the code block above. 

When using unique provider it makes sense when the actor blueprint is your context but maybe the check should be skipped if the blueprint is a widget blueprint? Its possible you addressed this in a recent change. 

Or maybe I am misunderstanding the concept of Unique Provider. It seems like a streamlined way to make unique instances for Actors without having to go through the FName Unique Key stuff that is provided in the cached viewmodels.

**Comment by DoubleDeez** [comment]
Ah yeah, that's not what Unique is meant for - the view models created by the Unique provider are meant to be one-off self-initializing view models that don't need to be referenced from multiple Views. They only exist while the View that binds to it exists and are destroyed when the View is destroyed. So in that case, your only context is the View with the Unique View Model Assignment (your user widget in your case).

I'm _very_ behind on documentation since I've been focusing on new features and QoL improvements but I plan on fleshing out the details in the wiki.

It sounds like you were expecting the Unique Provider to create a type of Singleton View Model instance?

I have a plan for a Blackboard-like Provider that might be able to fill that role. The view model assignment on the actor would automatically create and initialize the view model then push it into the blackboard, then the view model assignment on your widget would automatically grab the view model from the blackboard whenever it changed.

That would be _similar_ to the Cached provider, but would allow Views to bind to specific view models without needing a specialized Cache Lifetime. Is that the functionality you were looking for?

**Comment by Maxproz** [comment]
Well, glad I asked because I convinced myself that the context shouldn't be the widget.

> That would be similar to the Cached provider, but would allow Views to bind to specific view models without needing a specialized Cache Lifetime. Is that the functionality you were looking for?

Yeah something like that, but I have a few other ideas in the meantime. The blackboard provider sounds pretty cool, looking forward to it.

As always, thanks for the detailed response.
